ae_user:
    resource: "@AEUserBundle/Resources/config/routing.yml"
    #type:     annotation
    #prefix:   /

a_eplatform:
    resource: "@AEplatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mremi_contact_form:
    resource: "@MremiContactBundle/Resources/config/routing.xml"